### PR TITLE
Adds support for `run_reverse_migration`

### PR DESCRIPTION
**Pull request by jrobichaud**

### CODE REVIEW

**Comment by plumdog** [comment]
I like this - it might be worth adding a check at the start of `run_migration()` that `self._migration_run` is False and at the start of `run_reverse_migration` that `self._migration_run` is True, and raise an exception if not.

This way you can't write a test than looks like it runs the reverse migration but actually does nothing.

**Comment by jrobichaud** [comment]
Good point, I'll add that.

**Comment by jrobichaud** [comment]
BTW, there is duplicated code between the `django_migration` and `south_migration` that could be in the base class (`run_migration` and `run_reverse_migration`) should that be refactored?

**Comment by plumdog** [comment]
That's true - I'm not super worried about that really given that the logic will be pretty straightforward.

**Comment by jrobichaud** [comment]
I added the same check as `get_model_after`

**Comment by plumdog** [comment]
[Version 0.0.12](https://pypi.python.org/pypi/django-migration-testcase/0.0.12) tagged and released to PyPI.

Thanks for this PR!

**Comment by lynnco** [comment]
This is 💯 I was thinking about writing a reverse migration when I was working on a PR recently https://github.com/SexualHealthInnovations/callisto-core/pull/142. Didn't know the feature hadn't been added yet

**Comment by plumdog** [comment]
@lynnco (I should probably make sure this is clear in the docs but...) Reverse migrations were already supported if you put something like `before = 0002` and `after = 0001` and then `self.run_migration()` will run the reverse of the `0002` migration.

*But* what this PR does add is the ability to run a migration up then down again in the same test. Eg: set some data up, run it forwards, check it looks right, run it backwards, check it goes back to how you expect. Which is quite a natural way of testing reverse migrations.

(Also, I love to know the sorts of things that the OSS stuff I've started is used on, and yours looks like an amazing project.)

**Comment by plumdog** [comment]
I've written some stuff [here](https://github.com/plumdog/django_migration_testcase#reverse-migrations) to doc-ify things a bit more. Hopefully helpful!

**Pull request merged**
