### PR TITLE
Adds idempotent transaction

### PR DESCRIPTION
**Pull request by jrobichaud**
This is the workaround discussed here:
https://github.com/plumdog/django_migration_testcase/issues/33

### CODE REVIEW

**Comment by jrobichaud** [comment]
It seems it works only with python 3.4+.

**Comment by jrobichaud** [comment]
@plumdog what else is needed to get this merged?

**Comment by plumdog** [comment]
@jrobichaud Sorry, it's been a while!

Code looks good to me.

It would probably be a good idea to add something to the README explaining what it does and when it should be used. Even if it is pretty basic to start with, if it's in the docs I will be less likely to forget about it.

**Comment by jrobichaud** [comment]
Ok good, I'll do that over the weekend.

**Comment by jrobichaud** [comment]
@plumdog, I added some documentation. Since it is advanced usage I didn't go too far in the description. Let me know if there is anything else. Thanks.

**Pull request merged**
